# Generated by Django 5.2.1 on 2025-05-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
