# Generated by Django 5.2.1 on 2025-05-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_remove_category_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
