# Generated by Django 5.2.1 on 2025-05-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_category_products_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_Products',
        ),
    ]
