# Generated by Django 5.2.1 on 2025-05-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_category_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_products',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
