# Generated by Django 5.2.1 on 2025-06-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
