# Generated by Django 5.2.1 on 2025-06-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_products',
            name='is_top_deal',
            field=models.BooleanField(default=False),
        ),
    ]
